config/routes.rb
Rails.application.routes.draw do
  
  resources :users do
    resources :deeds do
    end
  end

  root 'pages#homepage'

  get 'auth/facebook', as: "auth_provider"
  get 'auth/facebook/callback' => 'sessions#create'
  post 'auth/facebook/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')
  post 'auth/failure' => redirect('/')
  get 'signout' => 'sessions#destroy'
  post 'signout' => 'sessions#destroy'

  get 'connections' => 'pages#graph'

  get 'about' => 'pages#about'

  namespace :api do
    resources :users
  end
end

app/models/deed.rb
class Deed < ActiveRecord::Base

  belongs_to :user, foreign_key: "from_id"
  belongs_to :receiver, foreign_key: "to_id", class_name: "User"

  validates :body, presence: true, length: { maximum: 140 }
 
  validates :to_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :generate_token

  has_many :deeds, foreign_key: "from_id"

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      # pry
      user.provider = auth.provider 
      user.uid      = auth.uid
      user.name     = auth.info.name
      user.save
    end
  end
  
  def large_fb_image
    "https://graph.facebook.com/#{self.uid}/picture?type=large"
  end

  def small_fb_image
    "https://graph.facebook.com/#{self.uid}/picture?type=small"
  end

  def normal_fb_image
    "https://graph.facebook.com/#{self.uid}/picture?type=normal"
  end

  def generate_token
    self.token = SecureRandom.urlsafe_base64
  end

  validates :name, presence: true
  
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    # before_action :authenticate

    def index
      users = User.all
      render json: users.to_json(:include => :deeds), only: [:id, :name, :token, :referrer]
    end

    def show
      user = User.find(params[:id])
      render json: user.to_json(:include => :deeds), only: [:id, :name, :token, :referrer]    
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_deed

  def set_deed
  	@deed = Deed.new
  end

  def authenticate
    render json: 'Authentication required.' unless ApiKey.exists?(token: params[:token])
  end
 
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to root_path unless current_user
  end

end

app/controllers/deeds_controller.rb
class DeedsController < ApplicationController
  before_action :authorize

  def index
    @user = User.find(params[:user_id])
    @deeds = @user.deeds.all.order(created_at: :desc)
  end

  def new
    @deed = Deed.new
  end

  def create
    current_user = User.find(params[:user_id]) unless current_user
    current_user.deeds.new(params.require(:deed).permit!)
    current_user.save
    redirect_to user_deeds_path(current_user)

    # if current_user.save
    #   redirect_to user_deeds_path(current_user)
    # else
    #   render :new
    # end
  end

  def edit
    get_deed
  end

  def update
    get_deed
    
    if @deed.update(deed_params)
      redirect_to user_deeds_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    get_deed
    @deed.destroy
    redirect_to user_deeds_path(current_user)
  end

  private

  def deed_params
    params.require(:deed).permit!
  end

  def get_deed
    @deed = current_user.deeds.find(params[:id])
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def homepage
		if params[:ref_id]
			cookies[:referral] = params[:ref_id]
		end

		if current_user
			redirect_to user_path(current_user)
		else
			render :homepage
		end
	end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
  # Method creates session for user and sets the users referrer to the cookie set in
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user["id"]
    if user.referrer == nil
      if cookies[:referral]
        user.update(referrer: cookies[:referral])
      end
    end
    redirect_to user_path(current_user)
  end

  # Method to sign out users
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @referrer = User.find_by(token: @user.referrer)
  	@invited = User.where(referrer: @user.token)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/deeds/edit.html.erb
<div class="modal fade" id="deedmodal2" tabindex="-1" role="dialog" aria-labelledby="myEditModalLabel" aria-hidden="false">
	<div class="modal-dialog">
		<div class="modal-content" id="modal-edit-fields">
			
			<div class="modal-header">
				<div class="modal-title" id="myEditModalLabel">Edit Deed</div>
			</div>
			<div class="modal-body">
				<%= form_for [@deed.user, @deed] do |f| %>
					<div class="form-group">
						<%= f.text_field :to_id, placeholder: "I did a deed for...", class: "form-control id-width" %>
					</div>
					<div class="form-group">
						<%= f.text_area :body, placeholder: "What I did was...", class: "form-control body-width", rows: 6 %>
						<br>
						<%= f.submit "Update", class: "btn-custom-alt btn" %> <span><%= link_to "Cancel", user_deeds_path(current_user), class: "btn btn-custom-alt" %></span>
					</div>
				<% end %>
 			</div> <!-- Closes Edit Form -->
		</div>
	</div>
</div>

app/views/deeds/index.html.erb
<div class="container-fluid">
<%= render "partials/nav" %>
<%= render "partials/deedmodal" %>
<%= render "partials/deedmodal2" %>


<div class="deed-container">
	<div class="row">

		<!-- Deeds#Index Title Bar-->
		<div class="col-xs-6 text-left">
			<header class="completed-deeds-title"><strong><%= @user.name %>'s</strong> <small>Completed Deeds</small></header>
		</div>

		<!-- "Create deed" and "Back to profile" buttons -->
		<div class="col-xs-6 text-right">
			<% if @user == current_user %>
				<button type="button" class="btn btn-custom" data-toggle="modal" data-target="#deed-modal">Create Deed</button>
			<% end %>
			<%= link_to "Back to profile", user_path(@user), class: "btn btn-custom"%>
		</div>
	</div> <!-- Closes title bar -->

	<div class="row">
		<% @deeds.each do |d| %>
		<div class="col-md-4">
			<br>
			<div class="deed-card">
				<div class="deed-body">
					<%= d.body %>
				</div>	
				<% if @user == current_user %>
					<div class="deed-option">
						<%#= link_to "edit", edit_user_deed_path(d.user,d), class: "deed-link" %>


						<a class="deed-link" data-toggle="modal" data-target="#deed-modal2" data-remote="<%= edit_user_deed_path(d.user, d) %> #modal-edit-fields">edit</a>

						<!-- <a class="deed-link" data-toggle="modal" data-target="#edit-deed-modal">edit</a> -->
						
						 <span class="link-divider">|</span> 
						 <%= link_to "delete", user_deed_path(d.user, d), method: :delete, data: { confirm: "Are you sure?"}, class: "deed-link" %>
					</div>
				<% end %>

				<div class="deed-name">
					<strong><%= d.to_id %></strong>
				</div>	
			</div>
		</div>
		<% end %>
	</div> <!-- Closes Deed card -->

</div> <!-- Closes Deed container -->
</div>
<%#= link_to "edit", edit_user_deed_path(d.user, d), class: "deed-link" %>

app/views/deeds/new.html.erb
<!-- Possible delete, in modal now -->

<%= render "partials/nav" %>
<div class="container-fluid set-width">

	<div class="center-block1">
		<h1>New Deed</h1>

		<%= form_for @deed, url: user_deeds_path do |f| %>
		<div class="form-group">
			<%= f.text_field :to_id, placeholder: "Deed for...", class: "form-control id-width" %>
		</div>
		<div class="form-group">
			<%= f.text_area :body, placeholder: "Enter deed", class: "form-control body-width", rows: 6 %>
		</div>
		<%= f.submit "Submit", class: "btn-custom" %>
		<% end %>

		<br>
		<%= link_to "Back to Profile", user_path(current_user), class: "btn-custom" %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friendindeed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/pages/about.html.erb
<div class="container-fluid" id="page-top">
  <%= render "partials/nav" %>

  <h1 class="text-center" id="about-page-title">How to Use</h1>
  <p id="logo-about" class="text-center"><span class="bluegrey">friend</span><span class="white">indeed</span></p>
  <br>
  <div class="container">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="aboutTitle">1. Create an account using Facebook to join our community</div>
      <img class="aboutImage img-responsive" src="/assets/howto1.jpg" width="800px">
    </div>


    <div class="col-sm-8 col-sm-offset-2">
     <div class="aboutTitle">2. Write out the deeds you did for your friends</div>
     <img class="aboutImage img-responsive" src="/assets/howto2.jpg" width="800px">
   </div>        


   <div class="col-sm-8 col-sm-offset-2">
     <div class="aboutTitle">3. View your collection of deeds</div>
     <img class="aboutImage img-responsive" src="/assets/howto3.jpg" width="800px">
   </div>

   <div class="col-sm-8 col-sm-offset-2">
    <div class="aboutTitle">4. Share the app to pass it on and remember to tag your friends!</div>

    <img class="aboutImage img-responsive" src="/assets/howto4-1.png" width="800px">
  </div>

  <div class="col-sm-8 col-sm-offset-2">
    <div class="aboutTitle">5. See how your deeds influenced your friends and others!</div>

    <img class="aboutImage img-responsive" src="/assets/howto5.png" width="800px">
  </div>      
  <div class="dockBottom-last">
    <a class="page-scroll" href="#page-top"><i class="fa fa-arrow-up fa-4x arrow-color"></i></a>
    <p>back to top</p>
  </div>

</div><!-- closes howto box -->
</div><!--closes container-fluid -->

app/views/pages/graph.html.erb
<div class="container-fluid">
<%= render "partials/nav" %>

<h1 class="text-center"><strong>Connections on</strong> <p id="logo-about"><span class="bluegrey">friend</span><span class="white">indeed</span></p></h1>

<script>
    // d3.json("http://friendindeed.herokuapp.com/api/users", function(root){
      d3.json("http://friendindeed.herokuapp.com/api/users", function(root){
    
    var links =[];

    connections(root);

    function connections(people){
      var arr = people;
      var arrleng = arr.length;
      
      for (var i = 0; i < arrleng; i++) {
          if (arr[i]['referrer'] == null){
            arr[i]['referrer'] = arr[i]['token'];
            links.push({uid: arr[i]['uid'], source: arr[i], target: arr[i]});
          }
          else {
            links.push({uid: arr[i]['uid'], source: arr[i], target: arr[i], type: 'suit'});
          };
      };
    };
    
    var nodes = {};

    links.forEach(function(link) {
      link.source = nodes[link.source['referrer']] || (nodes[link.source['referrer']] = {name: link.source.name, token: link.source.token, referrer: link.source.referrer, uid: link.source.uid, id: link.source.id});
      link.target = nodes[link.target['token']] || (nodes[link.target['token']] = {name: link.target.name, token: link.target.token, referrer: link.target.referrer, uid: link.target.uid, id: link.target.id});
    });

    var width = 1200,
        height = 590;

    var force = d3.layout.force()
        .nodes(d3.values(nodes))
        .links(links)
        .size([width, height])
        .linkDistance(70)
        .charge(-300)
        .on("tick", tick)
        .start();

    var tip = d3.tip()
      .attr('class', 'd3-tip')
      .offset([-10, 0])
      .html(function(d) {
        return "<center><img src='https://graph.facebook.com/" + d.uid + "/picture?type=normal'><br><br><span style='color:white'>" + d.name + "</span></center>";
    });

    var svg = d3.select("body").append("svg")
        .attr("width", width + "px")
        .attr("height", height + "px")
        .style("background-color", "#fff")
        .style("box-shadow", "0 3px 9px rgba(0,0,0,.5)")
        .style("margin", "20px auto 20px auto")
        .style("display", "block");

    svg.call(tip);        
    // Per-type markers, as they don't inherit styles.
    svg.append("defs").selectAll("marker")
        .data(["suit", "licensing", "resolved"])
      .enter().append("marker")
        .attr("id", function(d) { return d; })
        .attr("viewBox", "0 -5 10 10")
        .attr("refX", 15)
        .attr("refY", -1.5)
        .attr("markerWidth", 6)
        .attr("markerHeight", 6)
        .attr("orient", "auto")
      .append("path")
        .attr("d", "M0,-5L10,0L0,5");

    var path = svg.append("g").selectAll("path")
        .data(force.links())
      .enter().append("path")
        .attr("class", function(d) { return "link " + d.type; })
        .attr("marker-end", function(d) {   return "url(#" + d.type + ")"; });

    var circle = svg.append("g").selectAll("circle")
        .data(force.nodes())
      .enter()
      .append("a")
        .attr("xlink:href", function(d) {return "../users/" + d.id})
      .append("circle")
        .attr("r", function(d){
          if (d.token == "<%= current_user.token %>"){
            return "15px"
          }
          else{
            return "6.5px"
          }
        })



        .style("fill", function(d){
          if (d.token == "<%= current_user.token %>"){
            return "yellow"
          }
          else{
            return "white"
          }
        })
        .on('mouseover', function(d){ 
          d3.select(this)
            .attr("r", "15px")
            .style("fill", "red")
            tip.show(d);
        })
        .on('mouseout', function(d){
                        console.log(d);
          d3.select(this)
            .attr("r", function(d){
              if (d.token == "<%= current_user.token %>"){
                return "15px"
              }
              else{
                return "6.5px"
              }

          })
            .style("fill", function(d){
                if (d.token == "<%= current_user.token %>"){
                  return "yellow"
                }
                else{
                  return "white"
                }
            })
            tip.hide(d)
        })
        .call(force.drag);

    var text = svg.append("g").selectAll("text")
        .data(force.nodes())
      .enter().append("text")
        .attr("x", 0)
        .attr("y", 0)

    // Use elliptical arc path segments to doubly-encode directionality.
    function tick() {
      path.attr("d", linkArc);
      circle.attr("transform", transform);
      text.attr("transform", transform);
    }

    function linkArc(d) {
      var dx = d.target.x - d.source.x, 
          dy = d.target.y - d.source.y,
          dr = Math.sqrt(dx * dx + dy * dy);
      return "M" + d.source.x + "," + d.source.y + "A" + dr + "," + dr + " 0 0,1 " + d.target.x + "," + d.target.y;
    }

    function transform(d) {
      return "translate(" + d.x + "," + d.y + ")";
    }
  });

</script>

</div>

app/views/pages/homepage.html.erb
<!-- Section 1 -->
<section id="intro">
</section>

<!-- second section - About -->
<div id="about" class="pad-section">
  <div class="container">
    <div class="row">
      <div class="col-md-6 text-center">
        <h1><small><div class="friendindeed fid_logo"><span class="bluegrey">friend</span><span class="white">indeed</span></div></h1>
        <p style="margin-top: 30px" class="lead">FriendIndeed is a way for people to connect with other people who want to promote genuine acts of selflessness. Our passion comes from being able to see regular people want to make change in the world with very small deeds.</p>
      </div>
      <div class="col-md-6">
        <div class="text-center" style="margin-top: 50px">
         <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in", class: "btn-signin"%>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /second section -->

<section id="middle-image">
</section>

<!-- third section - Services -->
<div id="howtouse" class="pad-section">
  <div class="container">
    <h2 class="text-center">How to Use</h2> <hr />
    <div class="row text-center">
      <div class="col-sm-3 col-xs-6">
        <i class="glyphicon glyphicon-user"> </i>
        <h4>Sign Up</h4>
        <p>Create a FriendIndeed account using Facebook to join our community of good doers.</p>
      </div>
      <div class="col-sm-3 col-xs-6">
        <i class="glyphicon glyphicon-heart"> </i>
        <h4>Add Deeds</h4>
        <p>Write out the deeds that you did for your friends. Make sure that they continue to pass on good will to others.</p>
      </div>
      <div class="col-sm-3 col-xs-6">
        <i class="glyphicon glyphicon-share"> </i>
        <h4>Share</h4>
        <p>Share the app on your friends' Facebook timelines. Other people who sign up by viewing the app will be connected to you.</p>
      </div>
      <div class="col-sm-3 col-xs-6">
        <i class="glyphicon glyphicon-refresh"> </i>
        <h4>View Connections!</h4>
        <p>See how your good deeds can influence your friends and even people you may not even know! Doing good things can be awesome and help promote altruism.</p>
      </div>
    </div>
  </div>
</div>
<!-- /third section -->

<footer>
  <div class="container">
    <p class="pull-left">App created by Daniel Kim, Scott Shin, Daniel Mendoza for General Assembly</p>
    <p class="text-right">Copyright &copy; FriendIndeed 2015</p>
  </div>
</footer>

app/views/partials/_deedmodal.html.erb
<!-- Create Deed Modal -->
<div class="modal fade" id="deed-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			
			<div class="modal-header">
				<div class="modal-title" id="myModalLabel">Create Deed</div>
			</div>
			<div class="modal-body">
				<%= form_for @deed, url: user_deeds_path(current_user) do |f| %>

				<div class="form-group">
					<%= f.text_field :to_id, placeholder: "I did a deed for...", class: "form-control id-width" %>
				</div>

				<div class="form-group">
					<%= f.text_area :body, placeholder: "What I did was...", class: "form-control body-width", rows: 6 %>
					<br>
					<%= f.submit "Submit", class: "btn-custom-alt" %> <button type="button" class="btn-custom-alt" data-dismiss="modal">Cancel</button>
				</div>
				<% end %>			
			</div>
		</div>
	</div>
</div>

app/views/partials/_deedmodal2.html.erb
<%#= render "partials/edit-deed-fields" %>
<!-- Create Deed Modal -->
<div class="modal fade" id="deed-modal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
				<div id="modal-edit-fields">
				</div>
		</div>
	</div>
</div>

app/views/partials/_nav.html.erb
<nav class='navbar navbar-default'>
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<!-- Logo -->
			<a href="/"><p class="navbar-text"><span class="bluegrey">friend</span><span class="white">indeed</span></p></a>
		</div>

		
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			
			<ul class="nav navbar-nav">
				<li class="active"><span class="sr-only">(current)</span></li>
				<li><%= link_to "profile", current_user, class: "li_override" %></li>
				<li><%= link_to "how to use", about_path, class: "li_override" %></li>
				<li><%= link_to "connections", connections_path, class: "li_override" %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right link-margin-override">
				<% if current_user %>
				Welcome <%= link_to current_user.name, current_user, class: "link_override" %>! | <%= link_to "Sign out", signout_path, class: "link_override" %>
				<% end %>	
			</ul>

		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
<hr id="nav_line">
</nav>

app/views/users/show.html.erb
<script>

// Javascript Code for Facebook Share button
FB = null;
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  // if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=1410296982600187&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));

 $(document).ready(function(){
    	$('#share_button').click(function(e){
    		e.preventDefault();
    		FB.ui(
    		{
    			method: 'share',
    			href: 'http://friendindeed.herokuapp.com/?ref_id=<%= @user.token %>',
    		}, function(response){});
    	});
    });
  
</script> 

  <div class="container-fluid">
	<%= render "partials/nav" %>
	<%= render "partials/deedmodal" %>

	<div class="col-sm-6 col-sm-offset-3 bg">				
		<!-- User Profile Title Bar -->
		<h1><%= @user.name %>'s profile</h1>

		<!-- User account type: Original User or Invited by -->
		<% if !!@referrer %>
		<h4>Invited by <%= link_to @referrer.name, user_path(@referrer), class: "invited_link" %></h4>
		<% end %>

		<hr>					

		<div class="col-md-5 col-md-offset-1">
			<div class="profilepic_box">
				<%= image_tag(@user.large_fb_image) %>

				<div class="btn-box">
					<% if @user == current_user %>

					<!-- Facebook Share button -->
					<a id="share_button" target="_blank" class="btn btn-custom-fb"><i class="fa fa-facebook-official fa-1x"></i> &nbsp;Share</a>

					<!-- Create deed button -->
					<button type="button" class="btn btn-custom-alt" data-toggle="modal" data-target="#deed-modal">Create Deed</button>
					<% end %>

					<!-- Show deed button -->
					<%= link_to "View Deeds", user_deeds_path(@user), class: "btn btn-custom-alt" %>

				</div>
			</div>
			<br><!-- Provides cushion at mdaller res -->
		</div>

		<div class="col-md-6">
			<div class="peopleInvitedTitle">People Invited</div>
			<% @invited.each do |i| %>
			<div class="peopleInvited"><%= link_to i.name, user_path(i), class: "peopleInvited" %></div>
			<% end %>

		</div>
	</div>
</div>